# Generated by Django 5.2.1 on 2025-05-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
