# Generated by Django 5.2.1 on 2025-06-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
